/**
 * make-fixtures — derive each negative fixture from the REAL register.
 *
 * Hand-written fixtures rot: the register grows a required field, the fixtures
 * keep the old shape, and every one of them starts failing schema validation
 * (V1) instead of the rule it was written to prove. The suite stays green —
 * exit 1 is exit 1 — while proving nothing about V2..V8.
 *
 * So each fixture is the real register with ONE targeted mutation. If the
 * register changes shape, the fixtures change with it, and each still fails for
 * exactly the reason its name claims.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { stringify } from 'yaml';
import { loadRegister, REPO, addDaysUTC, todayUTC, type Register } from './lib.ts';

const NEG = resolve(REPO, 'tests/negative');
mkdirSync(NEG, { recursive: true });

const base = loadRegister();
const clone = (): Register => JSON.parse(JSON.stringify(base)) as Register;

function emit(name: string, why: string, r: Register) {
  const header = `# NEGATIVE FIXTURE — MUST FAIL VALIDATION.\n# ${why}\n# Generated by scripts/make-fixtures.ts from data/credentials.yaml.\n`;
  writeFileSync(resolve(NEG, name), header + stringify(r), 'utf8');
}

/* n01 — V2: held, no identifier */
{
  const r = clone();
  const c = r.certifications.find((x) => x.id === 'iso-27001')!;
  delete c.identifier;
  emit('n01-held-without-identifier.yaml', 'V2: a held certification with no identifier is not checkable.', r);
}

/* n02 — V2: held, no primary source */
{
  const r = clone();
  const c = r.certifications.find((x) => x.id === 'iso-27001')!;
  delete c.evidence_url;
  emit('n02-held-without-evidence-url.yaml', 'V2: a held certification with no primary-source link cannot be verified.', r);
}

/* n03 — V3: ISO 42001 claimed as held */
{
  const r = clone();
  const c = r.certifications.find((x) => x.id === 'iso-42001')!;
  c.status = 'held';
  c.identifier = '00 000 00000 XXX';
  c.evidence_url = 'https://www.tuvsud.com/ms-zert';
  c.valid_from = '2026-07-13';
  c.valid_to = '2029-07-12';
  emit('n03-iso42001-marked-held.yaml', 'V3: no ISO 42001 certificate has been issued; held must be refused even when the other fields are present.', r);
}

/* n04 — V4: expired */
{
  const r = clone();
  const c = r.certifications.find((x) => x.id === 'iso-27001')!;
  c.valid_from = addDaysUTC(todayUTC(), -1200);
  c.valid_to = addDaysUTC(todayUTC(), -10);
  emit('n04-expired-certificate.yaml', 'V4: a certificate that expired ten days ago must not render as held.', r);
}

/* n05 — V6: logo with no permission block */
{
  const r = clone();
  const m = r.memberships.find((x) => x.id === 'gaia-x')!;
  m.logo = 'logos/gaia-x-members.svg';
  emit('n05-logo-without-permission.yaml', 'V6: a mark with no permission block in logos/LOGO-USAGE.md must not ship.', r);
}

/* n06 — V6: digest mismatch (points the recorded logo at a different file) */
{
  const r = clone();
  const m = r.memberships.find((x) => x.id === 'adra')!;
  m.logo = 'logos/adra-logotype-tampered.png';
  emit('n06-logo-sha256-mismatch.yaml', 'V6: the permission record names a digest; a file whose bytes differ must fail.', r);
}

/* n07 — V7: private contact data */
{
  const r = clone();
  r.organization.address = 'Musterweg 12 B, 10115 Berlin, Deutschland';
  r.contact.security = 'founder.private@gmail.com';
  emit('n07-private-contact-leaked.yaml', 'V7: a private street address and a personal mailbox must never reach a public file.', r);
}

process.stdout.write('make-fixtures: wrote 7 fixture(s) derived from the real register\n');
