/**
 * make-fixtures — derive each negative fixture from the REAL register.
 *
 * Hand-written fixtures rot: the register grows a required field, the fixtures
 * keep the old shape, and every one of them starts failing schema validation
 * (V1) instead of the rule it was written to prove. The suite stays green —
 * exit 1 is exit 1 — while proving nothing about V2..V8.
 *
 * So each fixture is the real register with ONE targeted mutation. If the
 * register changes shape, the fixtures change with it, and each still fails for
 * exactly the reason its name claims.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { stringify } from 'yaml';
import { loadRegister, REPO, addDaysUTC, todayUTC, type Register } from './lib.ts';

const NEG = resolve(REPO, 'tests/negative');
mkdirSync(NEG, { recursive: true });

const base = loadRegister();
const clone = (): Register => JSON.parse(JSON.stringify(base)) as Register;

function emit(name: string, why: string, r: Register) {
  const header = `# NEGATIVE FIXTURE — MUST FAIL VALIDATION.\n# ${why}\n# Generated by scripts/make-fixtures.ts from data/credentials.yaml.\n`;
  writeFileSync(resolve(NEG, name), header + stringify(r), 'utf8');
}

/* n01 — V2: held, no identifier */
{
  const r = clone();
  const c = r.certifications.find((x) => x.id === 'iso-27001')!;
  delete c.identifier;
  emit('n01-held-without-identifier.yaml', 'V2: a held certification with no identifier is not checkable.', r);
}

/* n02 — V2: held, no primary source */
{
  const r = clone();
  const c = r.certifications.find((x) => x.id === 'iso-27001')!;
  delete c.evidence_url;
  emit('n02-held-without-evidence-url.yaml', 'V2: a held certification with no primary-source link cannot be verified.', r);
}

/* n03 — V3: ISO 42001 claimed as held */
{
  const r = clone();
  const c = r.certifications.find((x) => x.id === 'iso-42001')!;
  c.status = 'held';
  c.identifier = '00 000 00000 XXX';
  c.evidence_url = 'https://www.tuvsud.com/ms-zert';
  c.valid_from = '2026-07-13';
  c.valid_to = '2029-07-12';
  emit('n03-iso42001-marked-held.yaml', 'V3: no ISO 42001 certificate has been issued; held must be refused even when the other fields are present.', r);
}

/* n04 — V4: expired */
{
  const r = clone();
  const c = r.certifications.find((x) => x.id === 'iso-27001')!;
  c.valid_from = addDaysUTC(todayUTC(), -1200);
  c.valid_to = addDaysUTC(todayUTC(), -10);
  emit('n04-expired-certificate.yaml', 'V4: a certificate that expired ten days ago must not render as held.', r);
}

/* n05 — V6: logo with no permission block */
{
  const r = clone();
  const m = r.memberships.find((x) => x.id === 'gaia-x')!;
  m.logo = 'logos/gaia-x-members.svg';
  emit('n05-logo-without-permission.yaml', 'V6: a mark with no permission block in logos/LOGO-USAGE.md must not ship.', r);
}

/* n06 — V6: digest mismatch (points the recorded logo at a different file) */
{
  const r = clone();
  const m = r.memberships.find((x) => x.id === 'adra')!;
  m.logo = 'logos/adra-logotype-tampered.png';
  emit('n06-logo-sha256-mismatch.yaml', 'V6: the permission record names a digest; a file whose bytes differ must fail.', r);
}

/* n07 — V7: private contact data */
{
  const r = clone();
  r.organization.address = 'Musterweg 12 B, 10115 Berlin, Deutschland';
  r.contact.security = 'founder.private@gmail.com';
  emit('n07-private-contact-leaked.yaml', 'V7: a private street address and a personal mailbox must never reach a public file.', r);
}


/* n12 — V10: a mark whose credential is not held */
{
  const r = clone();
  // RE-POINTED 2026-09-12, and the reason is the lesson.
  //
  // This fixture used ki-bundesverband because that membership was
  // verification_pending. It became HELD on a dated document — so a mark for
  // it is now legitimate, and the fixture kept reporting `ok` while going red
  // for an ENTIRELY DIFFERENT reason (its placeholder sha256 does not match
  // the file it names). It asserted a property of the register's DATA instead
  // of a property of the RULE, so a legitimate data change disarmed it in
  // silence and the suite still showed green.
  //
  // ISO 42001 is used instead: it is `in_progress`, and V3 forbids it from
  // ever being held, so no future data change can make this mark legitimate.
  // The digest is the REAL digest of the file named, so the only thing left
  // for V10 to object to is the unheld credential.
  r.marks.push({
    id: 'iso42001-mark',
    display_name: 'ISO/IEC 42001 mark (no such certificate exists)',
    credential_ref: 'iso-42001',
    file: 'logos/adra-logotype.png',
    sha256: '227d5dc739473f8649ee0d16ede2ba165870bc25fbb8aa9f9705e233c7b46600',
    grantor: 'TUV SUD Management Service GmbH',
    grantor_role: 'Certification body',
    permission_date: '2026-07-07',
    permission_evidence: 'Fixture only — no such certificate and no such permission exists. This fixture must FAIL.',
    source_url: 'https://www.tuvsud.com/ms-cert',
    usage_constraints: 'Fixture only.',
    surfaces: ['site_footer'],
  });
  emit('n12-mark-credential-not-held.yaml', 'V10: a mark may not display a credential whose status is not held.', r);
}

/* n13 — V10: recorded digest does not match the file */
{
  const r = clone();
  r.marks[1]!.sha256 = '0'.repeat(64);
  emit('n13-mark-sha256-mismatch.yaml', 'V10: the permission record names a digest; different bytes must fail.', r);
}

/* n14 — V10: no permission evidence */
{
  const r = clone();
  // Whitespace-padded so it satisfies the schema's minLength and reaches V10,
  // which trims before measuring. A short value stops at V1 and would prove
  // the schema bites rather than that V10 does.
  r.marks[1]!.permission_evidence = ' '.repeat(40);
  emit('n14-mark-without-permission-evidence.yaml', 'V10: evidence that is only whitespace is no evidence; V10 trims before measuring.', r);
}

/* n18 — V10: a natural person as grantor */
{
  const r = clone();
  // The organisation allowlist had two DEAD entries until 2026-09-12 (`\be\.V\.\b`
  // could never match after a literal dot; `Verband` was case-sensitive so it
  // missed "Bundesverband"). Repairing it widened what passes, so this fixture
  // pins what must still FAIL — otherwise the repair could quietly have turned
  // the rule off.
  r.marks[1]!.grantor = 'Amaya Garmendia';
  emit('n18-grantor-is-a-person.yaml', 'V10: a natural person may not be the recorded grantor of a public permission (R8).', r);
}

/* n19 — V10: the organisation allowlist must not be a blanket pass */
{
  const r = clone();
  // A person's name with an organisational WORD in it is still a person.
  r.marks[1]!.grantor = 'Jane Doe Institut';
  emit('n19-person-with-org-word.yaml', 'V10: "Institut" appended to a personal name must not launder it into an organisation.', r);
}

/* n20 — V12: document_on_request without a DATE in the reference */
{
  const r = clone();
  const m = r.memberships.find((x) => x.id === 'ki-bundesverband')!;
  m.status = 'held';
  m.evidence_tier = 'document_on_request';
  m.document_ref = 'KI Bundesverband Aufnahmebestaetigung';   // named, but undated
  emit('n20-document-ref-undated.yaml', 'V12: an undated document reference cannot be checked; document_on_request requires the date.', r);
}

/* n21 — V12: held, no public URL, no declared tier */
{
  const r = clone();
  // NOT ki-bundesverband any more: that entry now CARRIES a tier and a dated
  // document_ref, so stripping its URL left a perfectly valid record and the
  // fixture went red on something else. A fixture must control its own
  // premise. Adra has no tier, so removing its URL produces exactly the state
  // this rule judges.
  const m = r.memberships.find((x) => x.id === 'adra')!;
  m.status = 'held';
  delete (m as { evidence_url?: string | null }).evidence_url;
  delete (m as { evidence_tier?: string }).evidence_tier;
  delete (m as { document_ref?: string }).document_ref;
  emit('n21-held-without-url-or-tier.yaml', 'V12: a held credential must name HOW it is backed — a public URL or a dated document.', r);
}

/* n22 — V12: public_registry is a promise that a URL exists */
{
  const r = clone();
  // A MEMBERSHIP, because `registrations.evidence_url` is schema-REQUIRED:
  // deleting it fails V1 and the fixture never reaches V12, certifying a rule
  // it did not exercise. ki-bundesverband's evidence_url is nullable today,
  // which is exactly the state this rule exists to judge.
  const c = r.memberships.find((x) => x.id === 'ki-bundesverband')!;
  c.status = 'held';
  c.evidence_tier = 'public_registry';
  c.evidence_url = null;
  emit('n22-public-registry-without-url.yaml', 'V12: public_registry claims anyone can open the evidence, so the URL is mandatory.', r);
}

/* n23 — V2 after the tier change: held, no URL, no tier, STILL refused */
{
  const r = clone();
  // V2 was taught to accept a dated document (2026-09-12), because a
  // membership whose directory entry is not live has no URL to give. This
  // fixture pins what it must still REFUSE, so that relaxation cannot quietly
  // decay into "held needs nothing at all".
  const m = r.memberships.find((x) => x.id === 'gaia-x')!;
  m.status = 'held';
  delete (m as { evidence_url?: string | null }).evidence_url;
  delete (m as { evidence_tier?: string }).evidence_tier;
  delete (m as { document_ref?: string }).document_ref;
  emit('n23-held-no-url-no-tier.yaml', 'V2: held with neither a primary-source link nor a dated document must still fail.', r);
}

/* n24 — V13: a render height edited without re-deriving it */
{
  const r = clone();
  // box_height_px is what the site renders AND what the app's resolution gate
  // measures density against. A hand-edited value would desynchronise the two
  // silently, so it must follow from the stored measurements.
  r.marks[0]!.render!.box_height_px = 40;
  emit('n24-render-height-not-derived.yaml', 'V13: box_height_px must follow from the stored measurements via the policy formula.', r);
}

/* n25 — V13: a mark rendered on the site with no measurements at all */
{
  const r = clone();
  delete r.marks[1]!.render;
  emit('n25-rendered-mark-without-measurements.yaml', 'V13: a mark with a site_path must carry its measured render block.', r);
}

/* n16 — V11: blocked evidence link with no human verification */
{
  const r = clone();
  // The register is ALREADY in this state for two entries, so the fixture
  // pins the rule rather than inventing a condition.
  const c = r.certifications.find((x) => x.id === 'iso-27001')!;
  c.machine_checkable = false;
  delete c.last_human_verified;
  emit('n16-blocked-without-human-verify.yaml', 'V11: an un-machine-checkable link needs a dated human confirmation.', r);
}

/* n17 — V11: human verification older than the 180-day limit */
{
  const r = clone();
  const c = r.certifications.find((x) => x.id === 'iso-27001')!;
  c.machine_checkable = false;
  c.last_human_verified = addDaysUTC(todayUTC(), -181);
  c.human_verified_by = 'compliance';
  emit('n17-human-verify-expired.yaml', 'V11: a confirmation 181 days old has expired; the limit is 180.', r);
}

process.stdout.write('make-fixtures: wrote 20 fixture(s) derived from the real register\n');
